---
title: DevOps Loft Blog
email: "liora [- @ -] lmb.co.il"
description: >
  To be the meeting point for DevOps practitioners, past, present and future
minimal_mistakes_skin: dark
search: true
logo: "/assets/images/logo.png"
repository: "devopsloft/devopsloft.github.io"
domain: devopsloft.github.io
url: https://devopsloft.github.io

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: IL

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Liora Milbaum"
  avatar: "/assets/images/lmilbaum.jpg"
  bio: "I am DevOps Engineer with a twist"
  location: "Tel Aviv, Israel"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lmilbaum"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

exclude:
  - README.md
