title: DevOps Loft Blog
name: "Liora Milbaum"
email: "liora [- @ -] lmb.co.il"
description: To be the meeting point for DevOps practitioners, past, present and future
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"