---
name: build-deploy-test

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Build jekyll
        uses: actions/jekyll-build-pages@v1.0.9

      - name: Archive
        run: tar --dereference --hard-dereference --directory _site/ -cvf artifact.tar .

      - name: Upload
        uses: actions/upload-artifact@v4.3.1
        with:
          name: github-pages
          path: ./artifact.tar
          if-no-files-found: warn

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy
        run: echo "TBD"
