---
name: pre_commit

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: actions/setup-python@v4.7.0
      - uses: pre-commit/action@v3.0.0
